-- HD2-Addon: mods/alomare/ragdoll_on_command
-- Ragdoll On Command by Alomare.
--
-- Ragdolls your Helldiver when you press the "Ragdoll" key of Mod Bindings Menu (Options > Controls > MODS; it
-- starts unbound). It runs the game's own knockdown sequence on the local Helldiver: not already ragdolled, allowed
-- right now (the game refuses while diving, swimming, climbing and the like), then start. The game ends the ragdoll
-- and stands the Helldiver up by itself, as after an explosion.
--
-- The local Helldiver is found as the game's own "is this the local avatar" check finds it: the local player's
-- unit, its entity, then the avatar manager's index for that entity. Every native function is called only after
-- that chain was read (with ReadProcessMemory, which fails instead of crashing) the same frame and the ragdoll
-- state names the same entity.
-- Everything native is found in game.dll by code signatures (first at this build's addresses, else by a search of
-- its executable sections spread over frames, where a signature must match exactly once), and structure offsets
-- are read from the matched code. If anything is missing, the mod does nothing.
-- Status: %LOCALAPPDATA%\CowboyBingus\Helldivers2\Logs\RagdollOnCommand_STATUS.log (first line = verdict).
if rawget(_G, 'RagdollOnCommand') then return end

local ffi = require('ffi')
local bit = require('bit')

local M = {version = '1', frames = 0, errors = 0}
rawset(_G, 'RagdollOnCommand', M)

local loader = rawget(_G, 'CowboyBingusModLoader')

---------------------------------------------------------------------------------------
-- The game's code

-- BEGIN SIGNATURES (generated by research/signatures.py; game.dll build 25480438 addresses)
local SIGS = {
    {name = 'local_avatar', rva = 0xa40076, text = '48 8B 05 ?? ?? ?? ?? 48 8B D9 83 B8 ?? ?? ?? ?? 00 74 ?? 8B 90 ?? ?? ?? ?? 48 8D 4C 24 30 E8 ?? ?? ?? ?? EB ?? 8B 05 ?? ?? ?? ?? 89 44 24 30 48 8D 44 24 30 8B 00 3B 05 ?? ?? ?? ?? 74 ?? 48 8B 0D ?? ?? ?? ?? 45 33 C0 48 89 74 24 38 44 8B 89 ?? ?? ?? ?? 44 8B 91 ?? ?? ?? ?? 44 0F AF D0 41 8D 71 FF 45 85 C9 74 ?? 4C 8B 99 ?? ?? ?? ?? 48 89 7C 24 40 8B B9 ?? ?? ?? ?? 8B CE 43 8D 14 10 48 23 D1 41 8B 0C D3 3B CF 74 ?? 3B C8 74 ?? 41 FF C0 45 3B C1 72 ?? 48 8B 7C 24 40 48 8B 74 24 38 0F B6 83 54 0F 1A 00 88 83 55 0F 1A 00',
     fields = {players = {'rip', {3}, {7}}, local_active = {'u32', {12}}, local_unit = {'u32', {21}}, unit_entity = {'call', {31}, {35}}, no_entity = {'rip', {56}, {60}}, avatars = {'rip', {65}, {69}}, avatar_cap = {'u32', {80}}, avatar_mult = {'u32', {87}}, avatar_map = {'u32', {107}}, avatar_empty = {'u32', {118}}}},
    {name = 'unit_lookup', rva = 0xfd9ba0, text = '48 83 EC 08 4C 8B 1D ?? ?? ?? ?? 44 8B C2 4C 8B C9 81 FA ?? ?? ?? ?? 75 ?? 8B 05 ?? ?? ?? ?? 89 01 48 8B C1 48 83 C4 08 C3 45 8B 93 ?? ?? ?? ?? 33 D2 48 89 5C 24 10 41 8B 9B ?? ?? ?? ?? 48 89 6C 24 18 41 0F AF D8 41 8D 6A FF 48 89 74 24 20 48 89 3C 24 45 85 D2 74 ?? 49 8B BB ?? ?? ?? ?? 41 8B B3 ?? ?? ?? ?? 66 0F 1F 84 00 00 00 00 00 8B C5 8D 0C 1A 48 23 C8 48 8D 04 CF 8B 0C CF 3B CE 74 ?? 41 3B C8 74 ?? FF C2 41 3B D2 72 ?? 33 C0 48 8B 3C 24 48 8B 74 24 20 48 8B 6C 24 18 48 8B 5C 24 10 44 39 00 75 ?? 8B 40 04 48 8D 04 40 48 8D 80 ?? ?? ?? ?? 49 8D 04 C3',
     fields = {owner = {'rip', {7}, {11}}, no_unit = {'u32', {19}}, unit_cap = {'u32', {44}}, unit_mult = {'u32', {58}}, unit_map = {'u32', {92}}, unit_empty = {'u32', {99}}, entity_ids = {'u32', {179}}}},
    {name = 'knockdown', rva = 0x833680, text = '48 69 C5 ?? ?? ?? ?? 48 8D 9E ?? ?? ?? ?? 48 03 D8 48 8B CB E8 ?? ?? ?? ?? 84 C0 75 ?? 48 8B CB E8 ?? ?? ?? ?? 84 C0 74 ?? 33 D2 48 8B CB E8 ?? ?? ?? ??',
     fields = {avatar_stride = {'u32', {3}}, ragdoll_state = {'u32', {10}}, is_ragdolled = {'call', {21}, {25}}, can_ragdoll = {'call', {33}, {37}}, start_ragdoll = {'call', {47}, {51}}}},
    {name = 'ragdoll_check', rva = 0xa74700, text = '48 83 EC 08 8B 81 ?? ?? ?? ?? 3B 05 ?? ?? ?? ?? 75 ?? 32 C0 48 83 C4 08 C3 3B 05 ?? ?? ?? ?? 4C 8B 15 ?? ?? ?? ?? 75 ?? B8 FF FF FF FF EB ?? 45 8B 8A ?? ?? ?? ?? 45 33 C0 48 89 5C 24 10 41 8B 9A ?? ?? ?? ?? 48 89 6C 24 18 0F AF D8 41 8D 69 FF 48 89 74 24 20 48 89 3C 24 45 85 C9 74 ?? 49 8B BA ?? ?? ?? ?? 41 8B B2 ?? ?? ?? ?? 0F 1F 00 8B CD 41 8D 14 18 48 23 D1 8B 0C D7 4C 8D 1C D7 3B CE 74 ?? 3B C8 74 ?? 41 FF C0 45 3B C1 72 ?? B8 FF FF FF FF 48 8B 74 24 20 48 8B 6C 24 18 48 8B 5C 24 10 48 8B 3C 24 8B C8 48 69 C1 ?? ?? ?? ?? 4A 8B 84 10 ?? ?? ?? ?? 48 C1 E8 24 24 01',
     fields = {state_entity = {'u32', {6}}, no_entity = {'rip', {27}, {31}}, avatar_stride = {'u32', {173}}, flags = {'u32', {181}}, avatars = {'rip', {34}, {38}}, avatar_cap = {'u32', {50}}, avatar_mult = {'u32', {65}}, avatar_map = {'u32', {98}}, avatar_empty = {'u32', {105}}}},
    {name = 'ragdoll_flags', rva = 0xa748fa, optional = true, text = '48 69 C1 ?? ?? ?? ?? 48 B9 40 00 00 80 09 08 84 01 4A 85 8C 10 ?? ?? ?? ?? 75 ?? 42 F6 84 10 ?? ?? ?? ?? 02',
     fields = {avatar_stride = {'u32', {3}}, flags = {'u32', {21}}, state_bits = {'u32', {31}}}},
}
-- END SIGNATURES

-- BEGIN SIGNATURE ENGINE (tools/sigscan.lua, written by research/signatures.py: edit it there)
-- Signature engine v1: finds game.dll code by signatures and reads values from the matched code.
-- Canonical copy: tools/sigscan.lua in the workspace. Each mod's research/signatures.py writes this block and the
-- mod's SIGS table into its script (tools/sigspec.py), so every mod carries the same engine.
--
-- A signature is {name, rva, text, fields, optional}: text is hex bytes with '??' wildcards; rva is where the
-- generating build had it. fields = {field = {kind, {offset...}, {next...}}}: kind 'u8' / 'u32' (a value inside the
-- matched code), 'rip' (a global: the target of a rip-relative operand) or 'call' (a function: the target of a rel32
-- call); offset = each occurrence's byte position in the pattern, next = the end of its instruction. Every occurrence
-- must agree, and a field shared by several signatures must agree across them.
--
--   local code = sigscan.new(SIGS, read, base, validate)  -- read(address, size) -> string or nil; base = game.dll
--                                                        -- base; validate (optional) = {name = function(rva) -> bool}:
--                                                        -- extra checks a match must pass (decoys don't count)
--   code:start()                                 -- tries each signature at its rva; true when all were there
--   code:step()                                  -- else: one chunk of the search per call; true when finished
--   code.found[name] (rva), code.missing[name] (reason), code.values[field], code.problems (list)
local sigscan = {}
do
    local CHUNK, OVERLAP = 0x400000, 256

    local function u16(b, o) return b:byte(o + 1) + 256 * b:byte(o + 2) end
    local function u32(b, o)
        local x1, x2, x3, x4 = b:byte(o + 1, o + 4)
        return x1 + 256 * x2 + 65536 * x3 + 16777216 * x4
    end
    local function i32(b, o)
        local v = u32(b, o)
        return v >= 2147483648 and v - 4294967296 or v
    end

    local function parse(sig)
        local bytes = {}
        for part in sig.text:gmatch('%S+') do bytes[#bytes + 1] = part ~= '??' and tonumber(part, 16) or false end
        local best_at, best_len, at, len = 1, 0, nil, 0  -- the longest run of fixed bytes is searched for
        for i = 1, #bytes + 1 do
            if bytes[i] then
                if not at then at, len = i, 0 end
                len = len + 1
                if len > best_len then best_at, best_len = at, len end
            else
                at = nil
            end
        end
        local anchor = {}
        for i = best_at, best_at + best_len - 1 do anchor[#anchor + 1] = string.char(bytes[i]) end
        sig.bytes, sig.anchor, sig.anchor_at = bytes, table.concat(anchor), best_at - 1
    end

    local function matches(blob, pos, sig)  -- pos: 1-based start in blob
        local bytes = sig.bytes
        if pos < 1 or pos + #bytes - 1 > #blob then return false end
        for i = 1, #bytes do
            local b = bytes[i]
            if b and blob:byte(pos + i - 1) ~= b then return false end
        end
        return true
    end

    local Scanner = {}
    Scanner.__index = Scanner

    function sigscan.new(sigs, read, base, validate)
        return setmetatable({sigs = sigs, read = read, base = base, validate = validate or {}, found = {}, missing = {},
                             moved = {}, values = {}, problems = {}, scan = nil, done = false}, Scanner)
    end

    function Scanner:valid(name, rva)
        local check = self.validate[name]
        if not check then return true end
        local ok, good = pcall(check, rva)
        return ok and good and true or false
    end

    -- game.dll's sections: {rva, size, exec}.
    function Scanner:load_sections()
        local read, base = self.read, self.base
        local dos = read(base, 0x40)
        local pe = dos and dos:sub(1, 2) == 'MZ' and u32(dos, 0x3c)
        local nt = pe and pe < 0x10000 and read(base + pe, 0x18)
        if not nt or nt:sub(1, 4) ~= 'PE\0\0' then return nil end
        local count, opt = u16(nt, 6), u16(nt, 20)
        local headers = count <= 96 and read(base + pe + 24 + opt, count * 40)
        if not headers then return nil end
        local sections = {}
        for i = 0, count - 1 do
            local size, rva, flags = u32(headers, i * 40 + 8), u32(headers, i * 40 + 12), u32(headers, i * 40 + 36)
            if size > 0 then
                sections[#sections + 1] = {rva = rva, size = size, exec = math.floor(flags / 0x20000000) % 2 == 1}
            end
        end
        return sections
    end

    function Scanner:in_section(rva, exec)
        for _, s in ipairs(self.sections) do
            if s.exec == exec and rva >= s.rva and rva + 8 <= s.rva + s.size then return true end
        end
        return false
    end

    -- Tries every signature at its rva and starts a search for the others. True when all were there (done), false
    -- when a search started, nil and a reason when game.dll is unreadable.
    function Scanner:start()
        self.sections = self:load_sections()
        if not self.sections then return nil, 'game.dll headers unreadable' end
        local wanted = {}
        for _, sig in ipairs(self.sigs) do
            parse(sig)
            local blob = self.read(self.base + sig.rva, #sig.bytes)
            if blob and matches(blob, 1, sig) and self:valid(sig.name, sig.rva) then
                self.found[sig.name] = sig.rva
            else
                wanted[#wanted + 1] = sig
            end
        end
        if #wanted == 0 then
            self:resolve()
            return true
        end
        local exec = {}
        for _, s in ipairs(self.sections) do if s.exec then exec[#exec + 1] = s end end
        self.scan = {sections = exec, section = 1, offset = 0, wanted = wanted, hits = {}}
        for _, sig in ipairs(wanted) do self.scan.hits[sig.name] = {} end
        return false
    end

    -- One chunk of the search (every match is collected: a signature must match exactly once). True when finished.
    function Scanner:step()
        local scan = self.scan
        if not scan then return true end
        local s = scan.sections[scan.section]
        if s then
            local from = scan.offset
            local size = math.min(CHUNK + OVERLAP, s.size - from)
            local pieces = {}
            local blob = self.read(self.base + s.rva + from, size)
            if blob then
                pieces[1] = {from, blob}
            else
                for off = from, from + size - 1, 0x10000 do  -- skip unreadable pages
                    local piece = self.read(self.base + s.rva + off, math.min(0x10000 + OVERLAP, s.size - off))
                    if piece then pieces[#pieces + 1] = {off, piece} end
                end
            end
            for _, piece in ipairs(pieces) do
                local piece_from, data = piece[1], piece[2]
                for _, sig in ipairs(scan.wanted) do
                    local init = 1
                    while true do
                        local at = data:find(sig.anchor, init, true)
                        if not at then break end
                        local start = at - sig.anchor_at
                        local offset = piece_from + start - 1
                        -- Matches starting in the overlap belong to the next chunk.
                        if offset >= from and offset < from + CHUNK and matches(data, start, sig)
                           and self:valid(sig.name, s.rva + offset) then
                            local hits = scan.hits[sig.name]
                            hits[#hits + 1] = s.rva + offset
                        end
                        init = at + 1
                    end
                end
            end
            scan.offset = from + CHUNK
            if scan.offset >= s.size then scan.section, scan.offset = scan.section + 1, 0 end
            if scan.sections[scan.section] then return false end
        end
        for _, sig in ipairs(scan.wanted) do
            local hits = scan.hits[sig.name]
            if #hits == 1 then
                self.found[sig.name] = hits[1]
                self.moved[#self.moved + 1] = sig.name
            else
                self.missing[sig.name] = #hits == 0 and 'not found' or ('found ' .. #hits .. ' times')
            end
        end
        self.scan = nil
        self:resolve()
        return true
    end

    -- A field's value from the matched code; nil and a reason if its occurrences disagree or it points nowhere.
    function Scanner:field_value(sig, rva, spec)
        local blob = self.read(self.base + rva, #sig.bytes)
        if not blob then return nil, 'unreadable' end
        local value
        for k, off in ipairs(spec[2]) do
            local v
            if spec[1] == 'u8' then v = blob:byte(off + 1)
            elseif spec[1] == 'u32' then v = u32(blob, off)
            else v = rva + spec[3][k] + i32(blob, off) end
            if value and v ~= value then return nil, 'occurrences disagree' end
            value = v
        end
        if spec[1] == 'rip' and not self:in_section(value, false) then return nil, 'global not in a data section' end
        if spec[1] == 'call' and not self:in_section(value, true) then return nil, 'function not in a code section' end
        return value
    end

    -- Reads every field of the found signatures. A signature whose fields don't read becomes missing; a field that
    -- differs between signatures is dropped (nil) and listed in problems.
    function Scanner:resolve()
        local seen = {}
        for _, sig in ipairs(self.sigs) do
            local rva = self.found[sig.name]
            if rva then
                local got = {}
                for name, spec in pairs(sig.fields or {}) do
                    local v, why = self:field_value(sig, rva, spec)
                    if not v then
                        self.missing[sig.name] = string.format('field "%s" %s', name, why)
                        self.found[sig.name] = nil
                        got = nil
                        break
                    end
                    got[name] = v
                end
                for name, v in pairs(got or {}) do
                    if seen[name] ~= nil and seen[name] ~= v then
                        self.problems[#self.problems + 1] = string.format('"%s" differs between signatures', name)
                        seen[name] = false
                    elseif seen[name] == nil then
                        seen[name] = v
                    end
                end
            end
        end
        for name, v in pairs(seen) do self.values[name] = v or nil end
        self.done = true
    end

    -- The address of a found signature's match (plus an offset), or nil.
    function Scanner:address(name, offset)
        local rva = self.found[name]
        return rva and self.base + rva + (offset or 0)
    end

    -- Every missing signature as 'name (reason)', for logs and status files.
    function Scanner:missing_list()
        local out = {}
        for _, sig in ipairs(self.sigs) do
            if self.missing[sig.name] then out[#out + 1] = sig.name .. ' (' .. self.missing[sig.name] .. ')' end
        end
        return out
    end
end
-- END SIGNATURE ENGINE

---------------------------------------------------------------------------------------
-- Configuration

local BINDING = 'alomare.ragdoll_on_command.ragdoll'
local REQUIRED = {'local_avatar', 'unit_lookup', 'knockdown', 'ragdoll_check'}
local MAX_PROBES = 256       -- hash map probes per lookup
local MAX_AVATARS = 64      -- avatar indexes
local MAX_ENTITIES = 1048576
local RAGDOLL_BIT = 36      -- the ragdoll flag in the avatar's flag word (as the "is ragdolled" check reads it)
local WATCH_EVERY = 10      -- frames between checks while a ragdoll we started lasts
local WATCH_FRAMES = 3600   -- stop watching after this many frames

---------------------------------------------------------------------------------------
-- Logging and status

local function open_log(name)
    if loader and type(loader.open_log) == 'function' then
        local ok, f = pcall(loader.open_log, name)
        if ok then return f end
    end
end

local log_file = open_log('RagdollOnCommand.log')
local log_lines = 0

local function note(msg)
    if not log_file or log_lines >= 2000 then return end
    log_lines = log_lines + 1
    pcall(function()
        log_file:write(string.format('[f%d t%.1f] %s\n', M.frames, os.clock(), msg))
        log_file:flush()
    end)
end

local function write_status(lines)
    local f = open_log('RagdollOnCommand_STATUS.log')
    if not f then return end
    pcall(function()
        f:write(table.concat(lines, '\n') .. '\n')
        f:close()
    end)
end

---------------------------------------------------------------------------------------
-- Texts (mod_text: src/bingus_text.lua and locales/, placed ahead of this script by the build)

local T = mod_text.module
local tr = T.new(mod_text.locales.en, mod_text.locales.bundled, function(message) note('Text: ' .. message) end)

-- Mod Bindings Menu v2.1+ (version 3) takes texts as functions and calls them when its pages open, so they follow
-- the game's language; older versions take strings with byte limits, where a translation that does not fit stays
-- English. One function per key, so repeated registrations agree.
local text_functions = {}
local function host_text(host, key, bytes)
    if (tonumber(host.version) or 1) >= 3 then
        local fn = text_functions[key]
        if not fn then fn = function() return tr(key) end; text_functions[key] = fn end
        return fn
    end
    local value = tr(key)
    return #value <= bytes and value or tr.english[key]
end

---------------------------------------------------------------------------------------
-- Native memory

local native = {}

local function init_native()
    -- Declared one by one: another mod may already have declared some of them.
    for _, decl in ipairs({
        'void *GetCurrentProcess(void);',
        'void *GetModuleHandleA(const char *name);',
        'int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);',
    }) do pcall(ffi.cdef, decl) end
    -- The game's functions, declared once by name (a function pointer type string adds a C type on every use).
    if not pcall(ffi.typeof, 'RagdollOnCommandCheck') then
        ffi.cdef('typedef uint8_t (*RagdollOnCommandCheck)(uint64_t state);')
    end
    if not pcall(ffi.typeof, 'RagdollOnCommandStart') then
        ffi.cdef('typedef void (*RagdollOnCommandStart)(uint64_t state, uint64_t mode);')
    end
    local ok, k32 = pcall(ffi.load, 'kernel32')
    if not ok then return false, 'kernel32 unavailable' end
    native.k32, native.process = k32, k32.GetCurrentProcess()
    local game = k32.GetModuleHandleA('game.dll')
    if game == nil then return false, 'game.dll not loaded' end
    native.base = tonumber(ffi.cast('uint64_t', game))
    return true
end

local function read(address, size)
    local buf, got = ffi.new('uint8_t[?]', size), ffi.new('size_t[1]')
    if native.k32.ReadProcessMemory(native.process, ffi.cast('const void *', address), buf, size, got) == 0
       or tonumber(got[0]) ~= size then
        return nil
    end
    return ffi.string(buf, size)
end

local function u32(blob, offset)
    offset = offset or 0
    if not blob or #blob < offset + 4 then return nil end
    local v = ffi.new('uint32_t[1]')
    ffi.copy(v, blob:sub(offset + 1, offset + 4), 4)
    return tonumber(v[0])
end

local function read32(address) return u32(read(address, 4)) end

local function pointer(blob)
    if not blob or #blob ~= 8 then return nil end
    local v = ffi.new('uint64_t[1]')
    ffi.copy(v, blob, 8)
    local a = tonumber(v[0])
    if a < 0x10000 or a >= 0x800000000000 then return nil end
    return a
end

local function hex64(blob)
    if not blob or #blob ~= 8 then return 'unreadable' end
    return string.format('%08x%08x', u32(blob, 4), u32(blob, 0))
end

---------------------------------------------------------------------------------------
-- Resolution: signatures -> values and the game's functions

local code = nil  -- the signature engine
local V = {}      -- values read from the matched code (offsets; globals and functions as rvas)
local fn = nil    -- the game's functions: is_ragdolled, can_ragdoll, start_ragdoll

local function finish_resolution()
    V = code.values
    local missing = code:missing_list()
    local why = nil
    for _, name in ipairs(REQUIRED) do
        if not code.found[name] then why = 'code not found: ' .. table.concat(missing, ', ') end
    end
    if not why and #code.problems > 0 then why = table.concat(code.problems, ', ') end
    -- The functions the matched calls go to are the ones found by their own code.
    if not why and V.unit_entity ~= code.found.unit_lookup then why = 'the unit lookup differs from its call' end
    if not why and V.is_ragdolled ~= code.found.ragdoll_check then why = 'the ragdoll check differs from its call' end
    if not why then
        for _, name in ipairs({'players', 'local_active', 'local_unit', 'no_entity', 'avatars', 'avatar_cap',
                               'avatar_mult', 'avatar_map', 'avatar_empty', 'owner', 'no_unit', 'unit_cap',
                               'unit_mult', 'unit_map', 'unit_empty', 'entity_ids', 'avatar_stride',
                               'ragdoll_state', 'state_entity', 'flags', 'can_ragdoll', 'start_ragdoll'}) do
            if V[name] == nil then why = 'value missing: ' .. name; break end
        end
    end
    if why then
        note('Not available: ' .. why)
        write_status({'NOT AVAILABLE - ' .. why .. '; the game is unchanged', 'Ragdoll On Command ' .. M.version})
        M.retired = true
        return
    end
    local base = native.base
    fn = {is_ragdolled = ffi.cast('RagdollOnCommandCheck', base + V.is_ragdolled),
          can_ragdoll = ffi.cast('RagdollOnCommandCheck', base + V.can_ragdoll),
          start_ragdoll = ffi.cast('RagdollOnCommandStart', base + V.start_ragdoll)}
    M.ready = true
    if #code.moved > 0 then note('Moved code found: ' .. table.concat(code.moved, ', ')) end
    if #missing > 0 then note('Optional code not found: ' .. table.concat(missing, ', ')) end
    note(string.format('Ready: avatar state = avatars + 0x%x + index * 0x%x, entity at +0x%x', V.ragdoll_state,
                       V.avatar_stride, V.state_entity))
end

---------------------------------------------------------------------------------------
-- The local Helldiver

-- Low 32 bits of a * b (both 32-bit), exact in doubles.
local function mul32(a, b)
    local al, ah, bl, bh = a % 65536, math.floor(a / 65536), b % 65536, math.floor(b / 65536)
    return (al * bl + ((ah * bl + al * bh) % 65536) * 65536) % 4294967296
end

-- The game's id hash maps: rows of (key, value) u32 pairs at data, capacity a power of two, probed linearly from
-- key * mult. Returns the value, or nil and a reason.
local function lookup(base, map, cap, empty, mult, key)
    local data = pointer(read(base + map, 8))
    local capacity, empty_key, multiplier = read32(base + cap), read32(base + empty), read32(base + mult)
    if not (data and capacity and empty_key and multiplier) then return nil, 'map unreadable' end
    if capacity == 0 then return nil, 'map empty' end
    if capacity > 16777216 or bit.band(capacity, capacity - 1) ~= 0 then return nil, 'map capacity unexpected' end
    local hash = mul32(key, multiplier)
    for probe = 0, math.min(capacity, MAX_PROBES) - 1 do
        local row = read(data + ((hash + probe) % capacity) * 8, 8)
        if not row then return nil, 'map row unreadable' end
        local k = u32(row, 0)
        if k == empty_key then return nil, 'not in map' end
        if k == key then return u32(row, 4) end
    end
    return nil, 'not in map'
end

-- The local Helldiver's ragdoll state: {state, entity, index, avatars}, or nil and the reason.
local function local_avatar()
    local base = native.base
    local players = pointer(read(base + V.players, 8))
    if not players then return nil, 'no players' end
    if read32(players + V.local_active) == 0 then return nil, 'no local player' end
    local unit = read32(players + V.local_unit)
    if not unit then return nil, 'local unit unreadable' end
    if unit == V.no_unit then return nil, 'no Helldiver (no unit)' end
    local owner = pointer(read(base + V.owner, 8))
    if not owner then return nil, 'no entity owner' end
    local index, why = lookup(owner, V.unit_map, V.unit_cap, V.unit_empty, V.unit_mult, unit)
    if not index then return nil, 'unit ' .. unit .. ': ' .. why end
    if index >= MAX_ENTITIES then return nil, 'entity index unexpected' end
    local entity = read32(owner + V.entity_ids * 8 + index * 24)
    if not entity then return nil, 'entity unreadable' end
    if entity == read32(base + V.no_entity) then return nil, 'no Helldiver (no entity)' end
    local avatars = pointer(read(base + V.avatars, 8))
    if not avatars then return nil, 'no avatar manager' end
    local ai
    ai, why = lookup(avatars, V.avatar_map, V.avatar_cap, V.avatar_empty, V.avatar_mult, entity)
    if not ai then return nil, 'no Helldiver (entity ' .. entity .. ' ' .. why .. ')' end
    if ai >= MAX_AVATARS then return nil, 'avatar index unexpected' end
    local state = avatars + V.ragdoll_state + ai * V.avatar_stride
    if read32(state + V.state_entity) ~= entity then return nil, 'ragdoll state names another entity' end
    return {state = state, entity = entity, index = ai, avatars = avatars}
end

-- The avatar's flag words (the state bits from the optional signature), for the log.
local function flags_text(a)
    local at = a.avatars + a.index * V.avatar_stride
    return 'flags ' .. hex64(read(at + V.flags, 8)) .. ', state bits '
           .. (V.state_bits and hex64(read(at + V.state_bits, 8)) or 'unknown')
end

-- The ragdoll flag, read from memory (true, false, or nil if unreadable).
local function ragdoll_flag(a)
    local high = read32(a.avatars + a.index * V.avatar_stride + V.flags + 4)
    if not high then return nil end
    return bit.band(bit.rshift(high, RAGDOLL_BIT - 32), 1) == 1
end

---------------------------------------------------------------------------------------
-- Ragdoll

local watch = nil  -- a ragdoll we started: {entity, since}

local function ragdoll()
    local a, why = local_avatar()
    if not a then note('Ragdoll key: ' .. why); return end
    if fn.is_ragdolled(a.state) ~= 0 then note('Ragdoll key: already ragdolled'); return end
    if fn.can_ragdoll(a.state) == 0 then note('Ragdoll key: not allowed right now (' .. flags_text(a) .. ')'); return end
    note(string.format('Ragdoll key: starting (entity %d, avatar %d, %s)', a.entity, a.index, flags_text(a)))
    fn.start_ragdoll(a.state, 0)
    local now = fn.is_ragdolled(a.state) ~= 0
    note(now and 'Ragdolled' or 'Started, but not ragdolled (' .. flags_text(a) .. ')')
    if now then watch = {entity = a.entity, since = M.frames} end
end

-- Logs how long a ragdoll we started lasts (reads only; the game ends it).
local function watch_step()
    if not watch or M.frames % WATCH_EVERY ~= 0 then return end
    local a = local_avatar()
    local still
    if a and a.entity == watch.entity then still = ragdoll_flag(a) end
    if still and M.frames - watch.since < WATCH_FRAMES then return end
    note(string.format('Ragdoll %s after %d frames', still and 'still on, no longer watched' or
                       (a and a.entity == watch.entity and 'ended' or 'Helldiver gone'), M.frames - watch.since))
    watch = nil
end

---------------------------------------------------------------------------------------
-- Key: Mod Bindings Menu (it may load before or after this addon)

local key = {registered = false, down = false, warned = false}

local function key_pressed()
    local menu = rawget(_G, 'ModBindingsMenu')
    if not (type(menu) == 'table' and menu.api == 1) then
        if not key.warned and M.frames > 600 then
            key.warned = true
            note('Mod Bindings Menu not found')
            write_status({'WAITING - Mod Bindings Menu is not installed or not loaded; no key to press',
                          'Ragdoll On Command ' .. M.version})
        end
        return false
    end
    if not key.registered then
        key.registered = true
        local ok, res, why = pcall(menu.register_binding, BINDING, host_text(menu, 'binding.ragdoll', 64), nil,
                                   {category = host_text(menu, 'option.mod', 64)})
        note('Mod Bindings Menu binding: ' .. ((ok and res) and 'registered' or
             ('not registered (' .. tostring(ok and why or res) .. ')')))
        if ok and res and M.ready then
            write_status({'OK - set the Ragdoll key in Options > Controls > MODS', 'Ragdoll On Command ' .. M.version})
        end
    end
    local ok, down = pcall(menu.is_down, BINDING)
    down = ok and down and true or false
    local edge = down and not key.down
    key.down = down
    return edge
end

---------------------------------------------------------------------------------------
-- Frame step

local function start()
    M.started = true
    local ok, why = init_native()
    if not ok then
        write_status({'NOT AVAILABLE - ' .. why .. '; the game is unchanged', 'Ragdoll On Command ' .. M.version})
        note('Native access unavailable: ' .. why)
        M.retired = true
        return
    end
    -- The game's Text Language, for this mod's texts and every other mod's (bingus_text's shared registry).
    local tag, game_code = T.observe(read, native.base)
    note('Text language: ' .. tostring(T.language()) .. ' (game setting ' .. tostring(game_code or 'unreadable')
         .. ', tag ' .. tostring(tag) .. ')')
    code = sigscan.new(SIGS, read, native.base)
    local all, reason = code:start()
    if all == nil then
        write_status({'NOT AVAILABLE - ' .. reason .. '; the game is unchanged', 'Ragdoll On Command ' .. M.version})
        M.retired = true
    elseif all then
        finish_resolution()
    else
        note('Searching game.dll for moved code (game updated?)')
    end
end

local function frame()
    M.frames = M.frames + 1
    if not M.started then start(); return end
    if not M.ready then
        if code.scan and code:step() then finish_resolution() end
        return
    end
    if key_pressed() then ragdoll() end
    watch_step()
end

local original_update = rawget(_G, 'update')
update = function(dt, ...)
    if not M.retired then
        local ok, err = xpcall(frame, debug.traceback)
        if not ok then
            M.errors = M.errors + 1
            note('Error: ' .. tostring(err))
            if M.errors >= 5 then
                M.retired = true
                write_status({'STOPPED - repeated errors; the game is unchanged (see RagdollOnCommand.log)',
                              'Ragdoll On Command ' .. M.version})
            end
        end
    end
    if type(original_update) == 'function' then return original_update(dt, ...) end
end

note('Ragdoll On Command ' .. M.version .. ' loaded')
M._test = {values = function() return V end, local_avatar = function() return local_avatar() end}  -- offline checks
return M
